pub mod agents_config;
pub mod control;
pub mod daemon;
pub mod engine;
pub mod error;
pub mod event;
pub mod journal;
pub mod manager;
pub mod pid_lock;
pub mod session_meta;
pub mod session_store;
pub mod transport;

pub use agents_config::{AgentInfo, AgentPreset, AgentsConfigStatus, ModelInfo};
pub use control::{ClientCommand, ErrorCode, FireTarget, ServerEvent};
pub use daemon::{Daemon, DefaultTransportFactory, ServeOpts, TransportFactory};
pub use engine::{Attach, EngineOpts, InputLease, SessionEngine, SessionSpawnConfig};
pub use error::{Result, RoyError};
pub use event::{event_from_json, event_to_json, StopReason, TurnEvent};
pub use journal::{ArchivedJournal, Journal, JournalEntry, Seq};
pub use manager::SessionManager;
pub use pid_lock::{peek_pid, pid_alive, PidLock};
pub use session_meta::SessionMetadata;
pub use transport::{AcpConfig, AcpTransport, Handle, PermissionPolicy, Transport};
